export const products = [
  // Back to the Future
  {
    name: "DeLorean Time Machine Car Shell",
    slug: "delorean-time-machine-car-shell",
    category: "Back to the Future",
    description:
      "Authentic stainless steel car shell used in the filming of Back to the Future, complete with integrated light rigs.",
    images: [],
    price: 150000.0,
    brand: "Amblin Props",
    rating: 4.5,
    numReviews: 4,
    stock: 1,
    isFeatured: true,
  },
  {
    name: "Flux Capacitor Assembly",
    slug: "flux-capacitor-assembly",
    category: "Back to the Future",
    description:
      "The heart of time travel—a fully realized Mr. Fusion–style flux capacitor used on set.",
    images: [],
    price: 1999.99,
    brand: "Amblin Props",
    rating: 5.0,
    numReviews: 3,
    stock: 2,
    isFeatured: true,
  },
  {
    name: "Pink Hoverboard Prop",
    slug: "pink-hoverboard-prop",
    category: "Back to the Future",
    description:
      "The iconic pink hoverboard used by Marty in ’Back to the Future Part II’, complete with foot straps.",
    images: [],
    price: 349.99,
    brand: "Amblin Props",
    rating: 3.0,
    numReviews: 4,
    stock: 3,
    isFeatured: false,
    banner: null,
  },
  {
    name: "“Mr. Fusion” Home Energy Reactor Unit",
    slug: "mr-fusion-home-energy-reactor-unit",
    category: "Back to the Future",
    description:
      "The DeLorean’s “Mr. Fusion” reactor unit prop, complete with warning labels and weathered finish.",
    images: [],
    price: 1299.5,
    brand: "Amblin Props",
    rating: 4.67,
    numReviews: 3,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Marty’s Gibson ES-345 Guitar",
    slug: "martys-gibson-es-345-guitar",
    category: "Back to the Future",
    description:
      "The Gibson ES-345 Chris Perry used on set during the ‘Johnny B. Goode’ performance.",
    images: [],
    price: 799.99,
    brand: "Amblin Props",
    rating: 4.8,
    numReviews: 5,
    stock: 2,
    isFeatured: false,
    banner: null,
  },

  // The Lord of the Rings
  {
    name: "The One Ring",
    slug: "the-one-ring",
    category: "The Lord of the Rings",
    description:
      "The Weta Workshop–forged Ring of Power seen in all three films, complete with Elvish inscription.",
    images: [],
    price: 4999.99,
    brand: "Weta Workshop",
    rating: 4.8,
    numReviews: 5,
    stock: 1,
    isFeatured: true,
  },
  {
    name: "Sting (Elven Sword)",
    slug: "sting-elven-sword",
    category: "The Lord of the Rings",
    description:
      "Bilbo’s sword Sting, used by both Bilbo and Frodo, complete with glowing “Orc-sense” blade.",
    images: [],
    price: 2499.0,
    brand: "Weta Workshop",
    rating: 4.33,
    numReviews: 3,
    stock: 2,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Andúril (Reforged Sword)",
    slug: "anduril-reforged-sword",
    category: "The Lord of the Rings",
    description:
      "Aragorn’s sword Andúril, reforged from the shards of Narsil, complete with runic hilt.",
    images: [],
    price: 2999.5,
    brand: "Weta Workshop",
    rating: 4.75,
    numReviews: 4,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Evenstar Necklace",
    slug: "evenstar-necklace",
    category: "The Lord of the Rings",
    description:
      "Arwen’s Evenstar pendant, delivered to Aragorn, with silver filigree and crystal center.",
    images: [],
    price: 999.99,
    brand: "Weta Workshop",
    rating: 4.33,
    numReviews: 3,
    stock: 3,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Palantír of Orthanc",
    slug: "palantir-of-orthanc",
    category: "The Lord of the Rings",
    description:
      "Saruman’s seeing-stone prop from Orthanc, a polished black crystal sphere atop its stand.",
    images: [],
    price: 1299.0,
    brand: "Weta Workshop",
    rating: 5.0,
    numReviews: 3,
    stock: 1,
    isFeatured: false,
    banner: null,
  },

  // Harry Potter
  {
    name: "Harry’s Holly-and-Phoenix-Feather Wand",
    slug: "harrys-holly-and-phoenix-feather-wand",
    category: "Harry Potter",
    description:
      "Harry’s original wand from Ollivanders: holly wood with phoenix feather core.",
    images: [],
    price: 299.99,
    brand: "Warner Bros. Props",
    rating: 5.0,
    numReviews: 4,
    stock: 2,
    isFeatured: true,
  },
  {
    name: "The Sorting Hat",
    slug: "the-sorting-hat",
    category: "Harry Potter",
    description:
      "The talking Sorting Hat prop used in the Hogwarts Great Hall scenes.",
    images: [],
    price: 499.0,
    brand: "Warner Bros. Props",
    rating: 3.67,
    numReviews: 3,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Golden Snitch (Quidditch Prop)",
    slug: "golden-snitch-quidditch-prop",
    category: "Harry Potter",
    description:
      "The mechanical Golden Snitch used on set for flying Quidditch takes.",
    images: [],
    price: 199.99,
    brand: "Warner Bros. Props",
    rating: 3.67,
    numReviews: 3,
    stock: 4,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Marauder’s Map Manuscript",
    slug: "marauders-map-manuscript",
    category: "Harry Potter",
    description:
      "The hand-drawn Marauder’s Map prop, complete with parchment texture and detailed footprints.",
    images: [],
    price: 149.99,
    brand: "Warner Bros. Props",
    rating: 4.75,
    numReviews: 4,
    stock: 2,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Hogwarts Acceptance Letter",
    slug: "hogwarts-acceptance-letter",
    category: "Harry Potter",
    description:
      "Hermetically sealed envelope prop with Hogwarts crest wax seal, as seen in all films.",
    images: [],
    price: 49.99,
    brand: "Warner Bros. Props",
    rating: 2.67,
    numReviews: 3,
    stock: 10,
    isFeatured: false,
    banner: null,
  },

  // Star Wars
  {
    name: "Luke Skywalker’s Lightsaber Hilt",
    slug: "luke-skywalkers-lightsaber-hilt",
    category: "Star Wars",
    description:
      "Luke’s original Bespin-blue lightsaber hilt prop used in The Empire Strikes Back.",
    images: [],
    price: 3499.99,
    brand: "Lucasfilm Props",
    rating: 4.8,
    numReviews: 5,
    stock: 1,
    isFeatured: true,
  },
  {
    name: "Han Solo’s DL-44 Blaster Pistol",
    slug: "han-solos-dl-44-blaster-pistol",
    category: "Star Wars",
    description:
      "The DL-44 blaster used by Harrison Ford in the original trilogy.",
    images: [],
    price: 1299.99,
    brand: "Lucasfilm Props",
    rating: 4.0,
    numReviews: 3,
    stock: 2,
    isFeatured: false,
    banner: null,
  },
  {
    name: "R2-D2 Dome/Head Unit",
    slug: "r2-d2-dome-head-unit",
    category: "Star Wars",
    description:
      "R2-D2’s rotating dome head prop, complete with sensor lights and panels.",
    images: [],
    price: 999.99,
    brand: "Lucasfilm Props",
    rating: 5.0,
    numReviews: 3,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Princess Leia’s Hologram Projector",
    slug: "princess-leias-hologram-projector",
    category: "Star Wars",
    description:
      "The R2-mounted hologram projector prop used to transmit Leia’s distress call.",
    images: [],
    price: 499.99,
    brand: "Lucasfilm Props",
    rating: 4.33,
    numReviews: 3,
    stock: 2,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Chewbacca’s Bowcaster",
    slug: "chewbaccas-bowcaster",
    category: "Star Wars",
    description:
      "Chewbacca’s signature bowcaster used throughout the original trilogy.",
    images: [],
    price: 799.99,
    brand: "Lucasfilm Props",
    rating: 4.5,
    numReviews: 4,
    stock: 1,
    isFeatured: false,
    banner: null,
  },

  // Avengers: Endgame
  {
    name: "Captain America’s Hero-Worn Vibranium Shield",
    slug: "captain-americas-hero-worn-vibranium-shield",
    category: "Avengers: Endgame",
    description:
      "Chris Evans’ stunt-worn Vibranium shield from the final battle in Endgame.",
    images: [],
    price: 4999.0,
    brand: "Marvel Studios Props",
    rating: 5.0,
    numReviews: 5,
    stock: 1,
    isFeatured: true,
  },
  {
    name: "Mjölnir (Thor’s Hammer)",
    slug: "mjolnir-thors-hammer",
    category: "Avengers: Endgame",
    description:
      "Thor’s on-set prop Mjölnir, forged in Uru and wielded on-screen by Chris Hemsworth.",
    images: [],
    price: 2999.99,
    brand: "Marvel Studios Props",
    rating: 4.75,
    numReviews: 4,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Stormbreaker (Thor’s Axe Prop)",
    slug: "stormbreaker-thors-axe-prop",
    category: "Avengers: Endgame",
    description:
      "The gigantic Stormbreaker axe prop used by Thor in the final battle scenes.",
    images: [],
    price: 3499.5,
    brand: "Marvel Studios Props",
    rating: 4.33,
    numReviews: 3,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Iron Man’s Nano Gauntlet",
    slug: "iron-mans-nano-gauntlet",
    category: "Avengers: Endgame",
    description:
      "The wearable nano gauntlet prop used by Robert Downey Jr. to snap the Infinity Stones.",
    images: [],
    price: 2499.0,
    brand: "Marvel Studios Props",
    rating: 4.75,
    numReviews: 4,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Hawkeye’s Ronin Sword",
    slug: "hawkeyes-ronin-sword",
    category: "Avengers: Endgame",
    description:
      "Clint Barton’s dual-bladed Ronin sword prop used during the New York battle.",
    images: [],
    price: 899.99,
    brand: "Marvel Studios Props",
    rating: 3.33,
    numReviews: 3,
    stock: 1,
    isFeatured: false,
    banner: null,
  },
];
